### ISSUE TITLE
Wiki en live site

### ISSUE THREAD

**Issue by Nazneen05x** [Marwaxhello/connect-your-tribe-squad-page#1]
Wiki moet je nog aanzetten!😊
En een url maken in cyclic

**Comment by Marwaxhello** [comment]
Mijn site is nu live, had problemen met mijn github desktop maar is. u opgelost

**Comment by Marwaxhello** [comment]
Ik had een probleem met mijn Girhub desktop. Bij dit soort problemen ga ik altijd naar Justus! Zijn feedback aan mij was om mijn Github desktop opnieuw te installeren en nu is het opgelostt
